apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: batch-jobs
  name: job-creator
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]